# This is NOT an autogenerated Makefile from CMake.
# CMake builds are to be conducted out-of-source, ensured by going through this Makefile.

test:
	mkdir -p build && cd build && cmake .. && make && cd .. && ./build/clyra_tests

run:
	mkdir -p build && cd build && cmake .. && make && cd .. && ./build/clyra

.PHONY: test